import React from "react";
import { describe, expect, it, vi, afterEach, beforeEach } from "vitest";
import { fireEvent, render, screen, act, cleanup, within } from "@testing-library/react";
import { Spelling } from "../../../src/ui/src/features/spelling/Spelling";
import { AutoRecite, spokenMeaning } from "../../../src/ui/src/features/auto-recite/AutoRecite";
import { Flashcard } from "../../../src/ui/src/features/flashcard/Flashcard";
import App from "../../../src/ui/src/app/App";
const words = [{ id: "1", spelling: "word", meaning: "单词", example: "A new word." }, { id: "2", spelling: "next", meaning: "下一个" }];
let spoken: { text: string; lang: string; onend?: () => void }[];
beforeEach(() => {
  localStorage.clear(); spoken = [];
  vi.stubGlobal("SpeechSynthesisUtterance", class { lang = ""; constructor(public text: string) {} });
  vi.stubGlobal("speechSynthesis", { speak: vi.fn(u => spoken.push(u)), cancel: vi.fn(), getVoices: () => [] });
});
afterEach(() => { cleanup(); vi.useRealTimers(); vi.unstubAllGlobals(); });
const start = () => fireEvent.click(screen.getByText("开始学习"));
async function answer(value: string) {
  fireEvent.change(screen.getByLabelText("英文拼写"), { target: { value } });
  fireEvent.submit(screen.getByLabelText("英文拼写").closest("form")!);
  await screen.findByText(/拼写正确|拼写错误/);
}
describe("study interactions", () => {
  it.each(["word", "wrong"])("waits for manual navigation after answering %s", async value => {
    render(<Spelling words={words} />); start();
    await answer(value);
    vi.useFakeTimers();
    await act(async () => { await vi.advanceTimersByTimeAsync(10_000); });
    expect(screen.getByLabelText("英文拼写")).toHaveValue(value);
    expect(screen.getByText("背诵 · 1 / 2 · 已经背诵 1 个")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /下一个单词/ }));
    expect(screen.getByLabelText("英文拼写")).toHaveValue("");
    expect(spoken.at(-1)?.text).toBe("next");
  });
  it("saves words from spelling feedback once and restores them only for their owner", async () => {
    const view = render(<App />);
    fireEvent.change(screen.getByLabelText("用户名称"), { target: { value: "小明" } });
    fireEvent.click(screen.getByText("创建用户并开始"));
    fireEvent.click(screen.getByRole("button", { name: "背诵", exact: true })); start();
    await answer("remember");
    fireEvent.click(screen.getByRole("button", { name: "添加到生词库", exact: true }));
    expect(screen.getByRole("button", { name: "已添加到生词库" })).toBeDisabled();
    expect(screen.getByLabelText("英文拼写")).toHaveValue("remember");
    view.unmount(); render(<App />);
    fireEvent.click(screen.getByRole("button", { name: "背诵", exact: true }));
    expect(screen.getByRole("button", { name: "已添加到生词库" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: /下一个单词/ }));
    await answer("wrong");
    expect(screen.getByRole("button", { name: "已添加到生词库" })).toBeDisabled();
    fireEvent.click(screen.getByRole("button", { name: "生词表", exact: true }));
    expect(screen.getByText("生词表 · 2 个")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "切换用户" }));
    fireEvent.click(screen.getByRole("button", { name: /＋ 添加用户/ }));
    const form = screen.getByRole("region", { name: "添加用户" });
    fireEvent.change(within(form).getByLabelText("用户名称"), { target: { value: "小红" } });
    fireEvent.click(screen.getByText("创建用户并开始"));
    fireEvent.click(screen.getByRole("button", { name: "生词表", exact: true }));
    expect(screen.getByText("还没有生词。")).toBeInTheDocument();
  });
  it("hides the answer until submission, persists progress, scores and retries wrong words twice", async () => {
    const wrong = vi.fn(); const view = render(<Spelling words={words} onWrong={wrong} />);
    expect(screen.getByRole("spinbutton", { name: "本次背诵数量" })).toHaveValue(100); start();
    expect(screen.queryByText("单词")).not.toBeInTheDocument();
    expect(spoken[0].text).toBe("word");
    await answer("wrod"); expect(wrong).toHaveBeenCalledWith("1");
    fireEvent.click(screen.getByText(/下一个单词/)); view.unmount();
    render(<Spelling words={words} />); expect(spoken.at(-1)?.text).toBe("next");
    await answer("ＮＥＸＴ"); fireEvent.click(screen.getByText(/查看本轮结果/));
    expect(screen.getByText("50 分")).toBeInTheDocument();
    expect(screen.getByText("背诵 2 个 · 正确 1 个 · 错误 1 个")).toBeInTheDocument();
    fireEvent.click(screen.getByText("确认，开始错词复习"));
    await answer("word"); fireEvent.click(screen.getByText(/查看本轮结果/));
    await answer("bad"); fireEvent.click(screen.getByText(/查看本轮结果/));
    expect(screen.getByText(/错词复习 · 第 3 轮/)).toBeInTheDocument();
    await answer("word"); fireEvent.click(screen.getByText(/查看本轮结果/));
    expect(screen.getByText("本次背诵完成")).toBeInTheDocument();
  });
  it("reveals meaning and example after the default ten-second pause", async () => {
    vi.useFakeTimers();
    render(<Flashcard words={words} />); start();
    expect(screen.queryByText("单词")).not.toBeInTheDocument();
    await act(async () => { spoken[0].onend?.(); });
    expect(screen.queryByText("单词")).not.toBeInTheDocument();
    await act(async () => { await vi.advanceTimersByTimeAsync(9999); });
    expect(screen.queryByText("单词")).not.toBeInTheDocument();
    await act(async () => { await vi.advanceTimersByTimeAsync(1); });
    expect(screen.getByText("单词")).toBeInTheDocument();
    expect(screen.getByText("A new word.")).toBeInTheDocument();
    fireEvent.click(screen.getByText("记住了，下一个"));
    expect(screen.queryByText("下一个")).not.toBeInTheDocument();
  });
  it("repeats with a pause after every reading and cancels pending work on return", async () => {
    vi.useFakeTimers();
    const view = render(<Flashcard words={words} />);
    fireEvent.change(screen.getByLabelText("单词朗读次数"), { target: { value: "2" } });
    fireEvent.change(screen.getByLabelText("停顿时间（秒）"), { target: { value: "0.5" } });
    start();
    await act(async () => { spoken[0].onend?.(); });
    await act(async () => { await vi.advanceTimersByTimeAsync(499); });
    expect(spoken).toHaveLength(1);
    await act(async () => { await vi.advanceTimersByTimeAsync(1); });
    expect(spoken).toHaveLength(2);
    expect(screen.queryByText("单词")).not.toBeInTheDocument();
    await act(async () => { spoken[1].onend?.(); });
    await act(async () => { await vi.advanceTimersByTimeAsync(500); });
    expect(screen.getByText("单词")).toBeInTheDocument();
    fireEvent.click(screen.getByText("记住了，下一个"));
    await act(async () => { spoken[2].onend?.(); });
    fireEvent.click(screen.getByText("返回设置"));
    expect(screen.getByLabelText("起始单词位置")).toHaveValue(2);
    await act(async () => { await vi.runAllTimersAsync(); });
    expect(vi.getTimerCount()).toBe(0);
    expect(spoken).toHaveLength(3);
    start();
    const interrupted = spoken.at(-1)!;
    fireEvent.click(screen.getByText("返回设置"));
    expect(window.speechSynthesis.cancel).toHaveBeenCalled();
    await act(async () => { interrupted.onend?.(); await vi.runAllTimersAsync(); });
    expect(spoken).toHaveLength(4);
    view.unmount();
    render(<Flashcard words={words} />);
    expect(screen.getByLabelText("起始单词位置")).toHaveValue(2);
    expect(screen.getByLabelText("停顿时间（秒）")).toHaveValue(0.5);
    expect(screen.getByLabelText("单词朗读次数")).toHaveValue(2);
  });
  it("previews five words on either side, validates inputs and starts at the chosen position", () => {
    const book = Array.from({ length: 20 }, (_, i) => ({ id: String(i), spelling: `word${i + 1}` }));
    render(<Flashcard words={book} />);
    const position = screen.getByLabelText("起始单词位置");
    expect(screen.getAllByRole("listitem")).toHaveLength(6);
    fireEvent.change(position, { target: { value: "10" } });
    const items = screen.getAllByRole("listitem");
    expect(items).toHaveLength(11);
    expect(items[0]).toHaveTextContent(/^word5$/);
    expect(items[5]).toHaveAttribute("aria-current", "true");
    expect(items[10]).toHaveTextContent(/^word15$/);
    fireEvent.change(position, { target: { value: "20" } });
    expect(screen.getAllByRole("listitem")).toHaveLength(6);
    fireEvent.change(position, { target: { value: "21" } });
    expect(screen.queryByRole("list")).not.toBeInTheDocument();
    expect(screen.getByText("开始学习")).toBeDisabled();
    fireEvent.change(position, { target: { value: "20" } });
    for (const [label, invalid, valid] of [["停顿时间（秒）", "", "0"], ["单词朗读次数", "1.5", "1"]]) {
      fireEvent.change(screen.getByLabelText(label), { target: { value: invalid } });
      expect(screen.getByText("开始学习")).toBeDisabled();
      fireEvent.change(screen.getByLabelText(label), { target: { value: valid } });
    }
    start();
    expect(spoken[0].text).toBe("word20");
    expect(screen.getByText(/本次还剩 1 个/)).toBeInTheDocument();
  });
  it("navigates flashcards from setup with pagination, search and a bounded saved session", () => {
    const book = Array.from({ length: 51 }, (_, i) => ({ id: String(i), spelling: `word${i + 1}`, meaning: i === 50 ? "末尾" : "释义" }));
    const view = render(<Flashcard words={book} />);
    fireEvent.change(screen.getByLabelText("起始单词位置"), { target: { value: "51" } });
    fireEvent.click(screen.getByRole("button", { name: "单词导航" }));
    expect(spoken).toHaveLength(0);
    expect(screen.getAllByRole("listitem")).toHaveLength(1);
    expect(screen.getByRole("button", { name: "51. word51 末尾" })).toHaveAttribute("aria-current", "true");
    fireEvent.click(screen.getByText("上一页"));
    expect(screen.getAllByRole("listitem")).toHaveLength(50);
    const search = screen.getByLabelText("搜索单词、释义或位置");
    fireEvent.change(search, { target: { value: "missing" } });
    expect(screen.getByText("没有找到匹配的单词。")).toBeInTheDocument();
    fireEvent.change(search, { target: { value: "末尾" } });
    fireEvent.click(screen.getByRole("button", { name: "51. word51 末尾" }));
    expect(spoken.at(-1)?.text).toBe("word51");
    expect(screen.getByText(/本次还剩 1 个/)).toBeInTheDocument();
    view.unmount();
    render(<Flashcard words={book} />);
    expect(spoken.at(-1)?.text).toBe("word51");
    expect(screen.getByText(/本次还剩 1 个/)).toBeInTheDocument();
  });
  it("cancels flashcard speech and waits in navigation, resumes or jumps without stale reveals", async () => {
    vi.useFakeTimers();
    render(<Flashcard words={words} />);
    fireEvent.change(screen.getByLabelText("本次背诵数量"), { target: { value: "1" } });
    start();
    const oldSpeech = spoken[0];
    fireEvent.click(screen.getByRole("button", { name: "单词导航" }));
    expect(window.speechSynthesis.cancel).toHaveBeenCalled();
    await act(async () => { oldSpeech.onend?.(); await vi.runAllTimersAsync(); });
    expect(spoken).toHaveLength(1);
    fireEvent.click(screen.getByText("返回学习"));
    expect(spoken.at(-1)?.text).toBe("word");
    expect(screen.getByText("记住了，下一个")).toBeDisabled();
    await act(async () => { spoken.at(-1)?.onend?.(); });
    fireEvent.click(screen.getByRole("button", { name: "单词导航" }));
    await act(async () => { await vi.runAllTimersAsync(); });
    expect(vi.getTimerCount()).toBe(0);
    fireEvent.change(screen.getByLabelText("搜索单词、释义或位置"), { target: { value: "2" } });
    fireEvent.click(screen.getByRole("button", { name: "2. next 下一个" }));
    expect(spoken.at(-1)?.text).toBe("next");
    expect(screen.getByText(/本次还剩 1 个/)).toBeInTheDocument();
    expect(screen.queryByText("下一个")).not.toBeInTheDocument();
    await act(async () => { spoken.at(-1)?.onend?.(); await vi.advanceTimersByTimeAsync(10000); });
    expect(screen.getByText("下一个")).toBeInTheDocument();
    fireEvent.click(screen.getByText("记住了，下一个"));
    expect(screen.getByText("设置本次学习")).toBeInTheDocument();
  });
  it("reads English, Chinese, each letter and the whole word before waiting; cancels on exit", async () => {
    vi.useFakeTimers(); const view = render(<AutoRecite words={[words[0]]} />);
    fireEvent.click(screen.getByText("开始朗读"));
    expect(spoken[0]).toMatchObject({ text: "word", lang: "en-US" });
    for (let i = 0; i < 7; i++) await act(async () => { spoken[i].onend?.(); });
    expect(spoken.map(u => u.text)).toEqual(["word", "单词", "w", "o", "r", "d", "word"]);
    await act(async () => { vi.advanceTimersByTime(2999); }); expect(spoken).toHaveLength(7);
    await act(async () => { vi.advanceTimersByTime(1); }); expect(spoken[7].text).toBe("word");
    view.unmount(); expect(window.speechSynthesis.cancel).toHaveBeenCalled(); expect(vi.getTimerCount()).toBe(0);
  });
  it("omits part-of-speech labels in speech while preserving the displayed definition", async () => {
    render(<AutoRecite words={[{ id: "s", spelling: "suddenly", meaning: "adv. 突然地；adj. 突然的" }]} />);
    fireEvent.click(screen.getByText("开始朗读"));
    await act(async () => { spoken[0].onend?.(); });
    expect(spoken[1]).toMatchObject({ text: "突然地；突然的", lang: "zh-CN" });
    expect(screen.getByText("adv. 突然地；adj. 突然的")).toBeInTheDocument();
    expect(spokenMeaning("n. 名词；vt. 及物；vi. 不及物；prep. 在；pron. 代词")).toBe("名词；及物；不及物；在；代词");
    expect(spokenMeaning("普通释义，含有英文 road.")).toBe("普通释义，含有英文 road.");
  });
  it("pauses for navigation and starts a fresh bounded session at the selected word", async () => {
    render(<AutoRecite words={words} />);
    fireEvent.change(screen.getByLabelText("本次背诵单词数"), { target: { value: "1" } });
    fireEvent.click(screen.getByText("开始朗读"));
    const oldSpeech = spoken[0];
    fireEvent.click(screen.getByRole("button", { name: "单词导航" }));
    expect(window.speechSynthesis.cancel).toHaveBeenCalled();
    await act(async () => { oldSpeech.onend?.(); });
    expect(spoken).toHaveLength(1);
    fireEvent.change(screen.getByLabelText("搜索单词、释义或位置"), { target: { value: "next" } });
    fireEvent.click(screen.getByRole("button", { name: "2. next 下一个" }));
    expect(spoken.at(-1)?.text).toBe("next");
    expect(screen.getByText("本次 1 / 1 · 词书第 2 个")).toBeInTheDocument();
    expect(screen.getByText("上一个")).toBeDisabled();
    expect(screen.getByRole("button", { name: "下一个" })).toBeDisabled();
  });
  it("paginates the book and can select a starting word before playback", () => {
    render(<AutoRecite words={Array.from({ length: 51 }, (_, i) => ({ id: String(i), spelling: `word${i + 1}` }))} />);
    fireEvent.click(screen.getByRole("button", { name: "单词导航" }));
    expect(spoken).toHaveLength(0);
    expect(screen.getAllByRole("listitem")).toHaveLength(50);
    fireEvent.click(screen.getByText("下一页"));
    expect(screen.getAllByRole("listitem")).toHaveLength(1);
    fireEvent.change(screen.getByLabelText("搜索单词、释义或位置"), { target: { value: "missing" } });
    expect(screen.getByText("没有找到匹配的单词。")).toBeInTheDocument();
    fireEvent.change(screen.getByLabelText("搜索单词、释义或位置"), { target: { value: "51" } });
    fireEvent.click(screen.getByRole("button", { name: "51. word51" }));
    expect(spoken.at(-1)?.text).toBe("word51");
    expect(screen.getByText("本次 1 / 1 · 词书第 51 个")).toBeInTheDocument();
  });
  it("sets up a bounded session, automatically advances and replays from its starting position", async () => {
    vi.useFakeTimers();
    render(<AutoRecite words={[words[0], { id: "a", spelling: "a" }, { id: "b", spelling: "b" }, words[1]]} />);
    expect(spoken).toHaveLength(0);
    expect(screen.queryByText("A new word.")).not.toBeInTheDocument();
    fireEvent.change(screen.getByLabelText("起始单词位置"), { target: { value: "2" } });
    fireEvent.change(screen.getByLabelText("本次背诵单词数"), { target: { value: "2" } });
    fireEvent.change(screen.getByLabelText("每次朗诵次数"), { target: { value: "1" } });
    fireEvent.change(screen.getByLabelText("每次朗诵间隔（秒）"), { target: { value: "0.5" } });
    fireEvent.click(screen.getByText("开始朗读"));
    expect(screen.queryByRole("spinbutton")).not.toBeInTheDocument();
    expect(screen.getByText("上一个")).toBeDisabled();
    expect(spoken[0].text).toBe("a");
    for (let word = 0; word < 2; word++) {
      await act(async () => { spoken.at(-1)?.onend?.(); });
      await act(async () => { spoken.at(-1)?.onend?.(); });
      await act(async () => { spoken.at(-1)?.onend?.(); });
      await act(async () => { vi.advanceTimersByTime(500); });
    }
    expect(spoken.map(u => u.text)).toEqual(["a", "a", "a", "b", "b", "b"]);
    expect(screen.getByText("本轮播放完成")).toBeInTheDocument();
    expect(screen.getByRole("button", { name: "下一个" })).toBeDisabled();
    fireEvent.click(screen.getByText("重新播放"));
    expect(spoken.at(-1)?.text).toBe("a");
    fireEvent.click(screen.getByText("返回设置"));
    expect(window.speechSynthesis.cancel).toHaveBeenCalled();
    expect(screen.getByLabelText("起始单词位置")).toHaveValue(2);
    const length = spoken.length;
    await act(async () => { vi.runAllTimers(); });
    expect(spoken).toHaveLength(length);
  });
  it("validates settings and limits the session to the end of the book", () => {
    render(<AutoRecite words={words} />);
    fireEvent.change(screen.getByLabelText("起始单词位置"), { target: { value: "3" } });
    expect(screen.getByText("开始朗读")).toBeDisabled();
    fireEvent.change(screen.getByLabelText("起始单词位置"), { target: { value: "2" } });
    fireEvent.change(screen.getByLabelText("每次朗诵间隔（秒）"), { target: { value: "" } });
    expect(screen.getByText("开始朗读")).toBeDisabled();
    fireEvent.change(screen.getByLabelText("每次朗诵间隔（秒）"), { target: { value: "0" } });
    fireEvent.click(screen.getByText("开始朗读"));
    expect(screen.getByText("本次 1 / 1 · 词书第 2 个")).toBeInTheDocument();
    expect(spoken[0].text).toBe("next");
    fireEvent.click(screen.getByText("暂停"));
    expect(window.speechSynthesis.cancel).toHaveBeenCalled();
    fireEvent.click(screen.getByText("继续朗读"));
    expect(spoken.at(-1)?.text).toBe("next");
  });
  it("shares the selected book across navigation and remembers counts per mode", () => {
    render(<App />);
    fireEvent.change(screen.getByLabelText("用户名称"), { target: { value: "测试用户" } });
    fireEvent.click(screen.getByText("创建用户并开始"));
    expect(screen.getByRole("button", { name: "听说训练" })).toHaveAttribute("aria-expanded", "false");
    fireEvent.click(screen.getByRole("button", { name: "强化学习", exact: true }));
    fireEvent.change(screen.getByRole("spinbutton", { name: "本次背诵数量" }), { target: { value: "12" } });
    fireEvent.click(screen.getByRole("button", { name: /选书/ }));
    fireEvent.click(screen.getByRole("button", { name: /旅行英语/ }));
    fireEvent.click(screen.getByRole("button", { name: /强化学习/ }));
    expect(screen.getByRole("spinbutton", { name: "本次背诵数量" })).toHaveValue(12); start();
    expect(screen.getByText("ticket")).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "背诵", exact: true }));
    expect(screen.getByRole("spinbutton", { name: "本次背诵数量" })).toHaveValue(100);
  });
});
