[package]
name = "quicklang-shell"
version.workspace = true
edition.workspace = true
license.workspace = true
[lib]
name = "quicklang_shell"
crate-type = ["staticlib", "cdylib", "rlib"]
[[bin]]
name = "quicklang"
path = "src/main.rs"
[build-dependencies]
tauri-build = { version = "2", features = [] }
[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
serde.workspace = true
quicklang-domain.workspace = true
quicklang-typing-engine.workspace = true
quicklang-application.workspace = true
quicklang-storage-port.workspace = true
quicklang-storage-seekdb.workspace = true
serde_json.workspace = true
reqwest = { version = "=0.13.4", default-features = false, features = ["json", "multipart", "native-tls"] }

tempfile = "=3.27.0"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "3"
